name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - name: Setup Node
      uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
