name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Setup Node
      uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
