name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Setup Node
      uses: actions/setup-node@d6e3b5539ed7e5ccd26c3459e26c7c817f4e9068
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
